#!/bin/bash

pip install jupyter-server-proxy

#jupyter serverextension enable --sys-prefix --py jupyter_server_proxy

nvm install 12

cd theia

npm install yarn

npx yarn --cache-folder ./ycache && rm -rf ./ycache
export NODE_OPTIONS="--max_old_space_size=4096"
npx yarn theia build
npx yarn theia download:plugins
