#!/bin/bash

pip install jupyter-server-proxy

#jupyter serverextension enable --sys-prefix --py jupyter_server_proxy
curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash 
source ~/.profile
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm install 12

cd theia

npm --scripts-prepend-node-path /home/jovyan/.nvm/versions/node/v12.22.7/bin/node install yarn

npx yarn --cache-folder ./ycache && rm -rf ./ycache
export NODE_OPTIONS="--max_old_space_size=4096"
npx yarn theia build
npx yarn theia download:plugins
